services:
  elastic:
    image: elasticsearch:8.18.0
    user: "1000:1000"
    profiles:
      - service
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - /.docker-data/mp/search/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic
  search:
    build:
      dockerfile: dev.Dockerfile
      context: .docker/php
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - search
      - elastic
  search-web:
    extends: search
    profiles:
      - service
    ports:
      - 8090:8000
    entrypoint: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
  search-worker-artists:
    profiles:
      - workers
    extends:
      service: search
    command: >
      php bin/console messenger:consume amqp 
      --queues=artists.on_update_full.1
      --queues=artists.on_update_full.2
      --queues=artists.on_update_full.3
      --queues=artists.on_update_full.4
      --bus=handle.bus -vv -f 10
  search-worker-albums:
    profiles:
      - workers
    extends:
      service: search
    command: >
      php bin/console messenger:consume amqp 
      --queues=albums.on_update_full.1
      --queues=albums.on_update_full.2
      --queues=albums.on_update_full.3
      --queues=albums.on_update_full.4
      --bus=handle.bus -vv -f 10
  search-worker-tracks:
    profiles:
      - workers
    extends:
      service: search
    command: >
      php bin/console messenger:consume amqp 
      --queues=tracks.on_update.1
      --queues=tracks.on_update.2
      --queues=tracks.on_update.3
      --queues=tracks.on_update.4
      --bus=handle.bus -vv -f 10
networks:
  elastic:
    driver: bridge
  search:
    name: music-playground-search
    external: true