parameters:
    albumsIndexName: albums
    artistsIndexName: artists
    maxPaginationCount: 100
    maxQLength: 100

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Shared\Infrastructure\ElasticSearch\ClientFactory:
        arguments:
            - '%env(ELASTICSEARCH_HOSTS)%'

    elasticsearch.client:
        factory: ['@App\Shared\Infrastructure\ElasticSearch\ClientFactory', 'create']
        class: Elastic\Elasticsearch\Client

    App\Search\Infrastructure\Repository\ArtistRepository:
        arguments:
            $client: '@elasticsearch.client'
            $index: '%artistsIndexName%'

    App\Search\Infrastructure\Repository\AlbumRepository:
        arguments:
            $client: '@elasticsearch.client'
            $index: '%albumsIndexName%'

    App\Search\Infrastructure\Controller\AlbumController:
        arguments:
            $maxQLength: '%maxQLength%'
            $maxCount: '%maxPaginationCount%'

    App\Search\Infrastructure\Controller\ArtistController:
        arguments:
            $maxQLength: '%maxQLength%'
            $maxCount: '%maxPaginationCount%'
